import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import FlareCursor from "@/components/cursor";
import Footer from "@/components/footer";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600','700','800','900'],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} font-medium text-neutral-100 cursor-default lg:cursor-none`}
      >
        <FlareCursor />
        {children}
        <Footer />
      </body>
    </html>
  );
}
